In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.6.0'

In [13]:
# Array of arrays
tensor_a = torch.ones(3, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
# Random generated
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[3.6658e+33, 4.5743e-41],
        [3.6658e+33, 4.5743e-41]])


tensor([[0.6065, 0.3325],
        [0.3539, 0.2737]])

In [11]:
# Random generated
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.4238, 0.6683],
        [0.8460, 0.3962]])

In [12]:
# Operation
result = tensor_b + tensor_c
result

tensor([[1.0303, 1.0009],
        [1.1999, 0.6699]])

In [29]:
# Harcoded
result_two = torch.tensor(
    [
        [1.0303, 1.0009, 3],
        [1.1999, 0.6699, 3],
        [2.0303, 2.0009, 3],
        [2.1999, 2.6699, 3],
    ])
result_two

tensor([[1.0303, 1.0009, 3.0000],
        [1.1999, 0.6699, 3.0000],
        [2.0303, 2.0009, 3.0000],
        [2.1999, 2.6699, 3.0000]])

In [30]:
result_two.shape

torch.Size([4, 3])

In [34]:
reshaped = result_two.view(3,4)
reshaped

tensor([[1.0303, 1.0009, 3.0000, 1.1999],
        [0.6699, 3.0000, 2.0303, 2.0009],
        [3.0000, 2.1999, 2.6699, 3.0000]])

In [35]:
# Index access and replacing value
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)
points[0][1] = 2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [36]:
# generating tensor with numpy method
numpyArray = np.random.randn(2,2)

from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[-0.6980, -0.5016],
        [-0.4351,  0.7546]], dtype=torch.float64)

In [37]:
some_data = torch.tensor([
    [ 50000, 3.0, 3],
    [ 74000, 1.5, 1],
    [ 22000, 4.7, 4],
    [ 31000, 3.2, 3],
    [ 92000, 5.0, 5],
])

In [38]:
mean_some_data = torch.mean(some_data)
mean_some_data

tensor(17935.5605)

In [42]:
mean_some_data_dim_0 = torch.mean(some_data, dim=0)
print(mean_some_data_dim_0)
print(mean_some_data_dim_0[0], mean_some_data_dim_0[1], mean_some_data_dim_0[2])

tensor([5.3800e+04, 3.4800e+00, 3.2000e+00])
tensor(53800.) tensor(3.4800) tensor(3.2000)


In [57]:
mean_some_data_dim_1 = torch.mean(some_data, dim=1)
print(mean_some_data_dim_1)

tensor([16668.6660, 24667.5000,  7336.2329, 10335.3994, 30670.0000])
